
owncloud:
  container_name: owncloud
  image: owncloud
  ports:
   - 0.0.0.0:999:999
  links:
   - postgres:owncloud-db

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
