version: '2'
services:

  postgres:
    restart: on-failure:10
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=intriguedb
    volumes:
      - "db-data:/var/lib/postgresql/data"

  redis:
    image: redis
    expose:
      - "6379"

###########

#  intrigue-web:
#    build: https://github.com/intrigueio/intrigue-core.git
#    ports:
#      - "83:7777"
#    links:
#      - redis
#      - postgres
#    environment:
#      - INTRIGUE_ENV=docker
#      - REDIS_URI=redis://redis:6379/

#TO TEST
  intrigue:
    build:
      context: ./intrigue
    ports:
      - "83:7777"

# fail
  dashboard:
     build: 
       context: ./pereval-dash
     ports:
       - "86:9090" 

# checked
  cyberchef:
    image: mpepping/cyberchef
    ports:
      - "82:8000"  

# checked
  openwebspider:
    image: pantyusha/openwebspider
    ports:
      - "81:9999"

#  spiderfoot:
#    build: https://github.com/smicallef/spiderfoot.git
#    ports:
#      - "85:8080"

# http://localhost:84/wisemapping/c/login
  wisemapping:
    image: wisemapping/webapp
    ports:
      - "84:8080" # might go overdriven by spiderfoot?

# checked, works after a while
  etherpad:
    build:
      context: ./etherpad-lite
    ports:
      - "89:9001"

# ethercalc - copy from ethercalc/docker-compose.yml

volumes:
  db-data:
