version: '2'
services:

  postgres:
    restart: on-failure:10
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=intriguedb
    volumes:
      - "db-data:/var/lib/postgresql/data"

  redis:
    image: redis
    expose:
      - "6379"

###########
#TODO change the git link from pereval to original
#  intrigue-web: #check
#    build: https://github.com/pereval-team/intrigue-core.git
#    ports:
#      - "83:7777"
#    links:
#      - redis
#      - postgres
#    environment:
#      - INTRIGUE_ENV=docker
#      - REDIS_URI=redis://redis:6379/

  dashboard: #rebind
     build: 
       context: ./pereval-dash
     ports:
       - "86:86" 

#  cyberchef: 
#    image: mpepping/cyberchef
#    ports:
#      - "82:8000"  

  openwebspider:
    image: pantyusha/openwebspider
    ports:
      - "81:9999"

  spiderfoot: #check
    build: 
       context: ./spiderfoot
    ports:
      - "85:5001"

#  wisemapping: #check
#    image: wisemapping/webapp
#    ports:
#      - "84:8080"

  etherpad: #check
    build:
      context: ./etherpad-lite
    ports:
      - "88:9001"

########## FILE MANAGING ############

  nextcloud: 
    build:
      context: ./nextcloud
    ports:
      - "443:443"

########## TASK MANAGING ############

#  kanboard:
#    build:
#      context: ./kanboard
#    ports:
#     - "90:80"

volumes:
 db-data:
